language: python
sudo: required
dist: trusty
os: linux

python:
    - "3.6"
services:
    - docker

git:
    depth: false  # Ensure latest tag is pulled

branches:
    only:
        - master

env:
    global:
        - secure: "o4isEDi/jgj741PYg2GJDAVtLcr+rgnNUFyAKpTjD8C0zfYH7XK9Sf8M2+ymk2BsmVF47KxSI4L2Zzl86rUeSaGSz5UGPbI9MLlv+pge53Z7uPZAv015xxDCjzn44UfXYzG2G0nu0RZ8spX7wpf8fw6jYaBmKogwxxL2t2ys4PMgHZV/0z9AebUj9Byi125VmoE/nvvLeDogXiLkDrod/vRtltA/IrKaZiirXNSakeuY21mGM7KvU8crKC08xae2HBEUBzrYuW2lpULnxrDm/sOFOfumErcRalnCQVYjntvCKFneGgfsXXqp/JoLoxKaM19ACnW0jIfXJ/3BBo/AHtFeuLj+TE2kWtLVd1aNtmyMmElmmxiALLdTvclQ3UcPnkj0HavDnoppo3BXp7eQp4KFpxfIRETOpR6ZP/0gN+pQSEkMH6Ac8DHbDbqiXUN0quEMN0pbbl/78+sROfIaokHDxp6iqiTCpFKJBRnBBiz1C+36j+WKsVIT7YFYMt/keG3YqUmWj+pfXCL6Ghj4sUTHAgpSp2hSn6Ys6f4iwCpi8LC9O4pxsMJE7xGhPZqyP88XcLGt+R8D8HYrDuViCpSViLrIG66vwCmV92+2DwLWJOPQPXoJVtyZQz4qnfyAuig2rTqofIMMM0KtAWL6/0G+jUoZxds15Ymg5YbIRmE="

jobs:
    fast_finish: true

    include:
        - env: DOCS=true

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - ./continuous_integration/docker_hadoop/hcluster startup base -w .

install:
    - ./continuous_integration/docker_hadoop/hcluster exec -- ./workdir/continuous_integration/travis/install.sh

script:
    - set -e
    - ./continuous_integration/docker_hadoop/hcluster exec -- py.test workdir/skein/ -vv
    - ./continuous_integration/docker_hadoop/hcluster exec -- flake8 workdir/skein/
    - |
      if [[ "$DOCS" == "true" ]]; then
        ./continuous_integration/docker_hadoop/hcluster exec -- ./workdir/continuous_integration/travis/build_docs.sh
        if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
            pip install doctr
            doctr deploy . --built-docs docs/build/html/
        fi
      fi

notifications:
  email: false
